<?php 
/**
 * @name folders.config.inc
 * @description 
 * @date 29/03/2011
 * @author Eliran Pe'er
 * @team 
 */

	define('FOLDER_BASE', '../'); // Link to the base folder.
	define('FOLDER_SYSTEM_MODULES', FOLDER_BASE . 'Boot/Modules/');
	define('FOLDER_SYSTEM_INTERFACES', FOLDER_BASE . 'Boot/Interfaces/');
	define('FOLDER_APPLICATION', FOLDER_BASE . 'Application/');
	define('FOLDER_CONTROLLERS', FOLDER_APPLICATION . 'Controllers/');
	define('FOLDER_MODULES', FOLDER_APPLICATION . 'Modules/');
	define('FOLDER_VIEWS', FOLDER_APPLICATION . 'Views/');
	define('FOLDER_IMAGES', FOLDER_APPLICATION . 'Images/');
	define('FOLDER_LAYOUT', FOLDER_APPLICATION . 'Layout/');
	define('FOLDER_SCRIPTS', FOLDER_APPLICATION . 'Scripts/');
	define('FOLDER_STYLESHEETS', FOLDER_APPLICATION . 'Stylesheets/');
		
?>